version: "3.7"

services:
  database_shishapedia:
    image: postgres
    container_name: database_shishapedia
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=shishapedia
    volumes:
      - pgdata:/data/postgres
    networks:
      - shishapedia

  app:
    build: .
    container_name: api_shishapedia
    entrypoint: ./.docker/entrypoint.sh
    ports:
      - 3000:3000
    volumes:
      - .:/usr/app
      - nodemodules:/usr/app/node_modules
    networks:
      - shishapedia
    depends_on:
      - database_shishapedia

volumes:
  pgdata:
    driver: local
  nodemodules:

networks:
  shishapedia:
